# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout codes
      uses: actions/checkout@v4
    - name: Setup .NET 8.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release

  upload:
    runs-on: windows-latest
    
    strategy:
      matrix:
        version: [5, 6, 7, 8]

    needs: build
    steps:
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./bin/Release/net${{ matrix.version }}.0-windows/WinFormsPagination.dll

  merge:
    runs-on: windows-latest
    needs: upload
    steps:
      - name: Upload Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          pattern: net*-windows
          separate-directories: true